apiVersion: apps/v1
kind: Deployment
metadata:
  name: teardown-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: teardown-app
  template:
    metadata:
      labels:
        app: teardown-app
    spec:
      containers:
        - name: app
          image: nginx:1.29-alpine
